version: '2'

services:
  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: 
      - --path.procfs=/host/proc 
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100

  prometheus:
    image: prom/prometheus
    volumes:
      - ./volumes/prom/etc:/etc/prometheus
      - ./volumes/prom/data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention=5d
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
      - --web.enable-lifecycle
    ports:
      - 9090:9090

  influxdb:
    image: influxdb:alpine
    volumes:
      - ./volumes/influx/var:/var/lib/influxdb/
      - ./volumes/influx/rawdata:/mnt/
    ports:
      - 8086:8086
    env_file:
      - env.influxdb

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./volumes/grafana/etc:/etc/grafana
      - ./volumes/grafana/var:/var/lib/grafana
    env_file:
      - env.grafana
