datasources:
  # <string, required> name of the datasource. Required
- name: Prometheus
  type: prometheus
  access: proxy
  org_id: 1
  url: http://prometheus:9090
  password:
  user:
  database:
  basic_auth:
  basic_auth_user:
  basic_auth_password:
  with_credentials:
  is_default: false
  version: 1
  editable: true

- name: InfluxDB
  type: influxdb
  access: proxy
  org_id: 1
  url: http://influxdb:8086
  password: shop
  user: work
  database: workshop
  basic_auth:
  basic_auth_user:
  basic_auth_password:
  with_credentials:
  is_default: true
  version: 1
  editable: true

- name: InfluxDB-Internal
  type: influxdb
  access: proxy
  org_id: 1
  url: http://influxdb:8086
  password: shop
  user: work
  database: _internal
  basic_auth:
  basic_auth_user:
  basic_auth_password:
  with_credentials:
  is_default: false
  version: 1
  editable: true
