global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.

  external_labels:
    monitor: 'grafana_workshop'

#remote_write:
#- url: "http://influxdb:8086/api/v1/prom/write?u=user&p=pass&db=prometheus"

scrape_configs:
- job_name: 'prometheus'
  scrape_interval: 5s

  static_configs:
  - targets: ['prometheus:9090']

- job_name: 'node-exporter'
  dns_sd_configs:
  - names:
    - 'node-exporter'
    type: 'A'
    port: 9100
  # Alternative to DNS based discovery:
  #static_configs:
  #  - targets: ['node-exporter:9100']
